services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build: .
    command: uvicorn app.fastapi.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - redis
    ports:
      - "8000:8000"
    environment:
      - FASTAPI_BASE_URL=http://api:8000

  worker:
    build: .
    user: "1000:1000"
    command: celery -A app.fastapi.core.celery_app worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1

  dash:
    build: .
    command: python -m app.dash.main
    ports:
      - "8050:8050"
    depends_on:
      - api
