services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    environment:
      - REDIS_URL=redis://redis:6379/2

  api:
    build: .
    volumes:
      - ./fastapi_app:/app/fastapi_app
    command: uvicorn fastapi_app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/fastapi_app
    depends_on:
      - redis
    ports:
      - "8000:8000"
    environment:
      - FASTAPI_BASE_URL=http://api:8000

  worker:
    build: .
    user: "1000:1000"
    command: celery -A fastapi_app.core.celery_app worker --loglevel=INFO
    depends_on:
      - redis
    volumes:
      - ./fastapi_app:/app/fastapi_app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1

  dash:
    build: .
    volumes:
      - ./dash_app:/app/dash_app
    command: python -u -m dash_app.main
    ports:
      - "8050:8050"
    depends_on:
      - api
